INSERT INTO public.user (fullname, username, email, password, is_admin) VALUES ('Patrik Galina', 'pgalina', 'pgalina@chain-reaction.com', '$2a$12$pygemk1zrkmkO7u0ylov2uUz0QtAHoqW4uRoWiXaT6pu9IaBllbgS', false);
INSERT INTO public.user (fullname, username, email, password, is_admin) VALUES ('admin', 'admin', 'admin@chain-reaction.com', '$2a$12$HZU2IovUhhEvpP1mftH5qeAoKSQEvrqqDzBQSARdV.2I1MKX9ZJS.', true);

INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, rent_price_per_hour, image_path, type) VALUES ('Cowboy', 'Take the streets.', '4', 25, 70, 3.5, 18.9, 2990.00, 1, 3, true, 12, '/assets/e-bikes/cowboy-4/cowboy-4-white.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, rent_price_per_hour, image_path, type) VALUES ('Cowboy', 'Take the streets.', '4', 25, 70, 3.5, 18.9, 2990.00, 2, 0, true, 12, '/assets/e-bikes/cowboy-4/cowboy-4-dark-gray.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, rent_price_per_hour, image_path, type) VALUES ('Cowboy', 'Take the streets.', '4', 25, 70, 3.5, 18.9, 2990.00, 3, 5, true, 12, '/assets/e-bikes/cowboy-4/cowboy-4-black.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, rent_price_per_hour, image_path, type) VALUES ('Cowboy', 'Dream machine.', '4ST', 20, 70, 3, 19.2, 2590.00, 1, 0, true, 9, '/assets/e-bikes/cowboy-4st/cowboy-4st-white.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, rent_price_per_hour, image_path, type) VALUES ('Cowboy', 'Dream machine.', '4ST', 20, 70, 3, 19.2, 2590.00, 2, 3, true, 9, '/assets/e-bikes/cowboy-4st/cowboy-4st-dark-gray.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, rent_price_per_hour, image_path, type) VALUES ('Cowboy', 'Dream machine.', '4ST', 20, 70, 3, 19.2, 2590.00, 3, 2, true, 9, '/assets/e-bikes/cowboy-4st/cowboy-4st-black.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, image_path, type) VALUES ('Trek', 'Mountain beast.', 'Powerfly 4', 30, 85, 2.5, 16.8, 3299.00, 3, 3, false, '/assets/e-bikes/trek-powerfly-4/trek-powerfly-4-black.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, image_path, type) VALUES ('Trek', 'Mountain beast.', 'Powerfly 4', 30, 85, 2.5, 16.8, 3299.00, 2, 1, false, '/assets/e-bikes/trek-powerfly-4/trek-powerfly-4-gray.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, image_path, type) VALUES ('Trek', 'Road destroyer.', 'Rail 5', 32, 75, 4, 18.2, 3699.00, 3, 4, false, '/assets/e-bikes/trek-rail-5/trek-rail-5-black.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, image_path, type) VALUES ('Trek', 'Road destroyer.', 'Rail 5', 32, 75, 4, 18.2, 3699.00, 2, 2, false, '/assets/e-bikes/trek-rail-5/trek-rail-5-gray.png', 1);
INSERT INTO public.product (name, description, model, assist_speed, battery_range, charging_time, weight, price, color, available_quantity, for_rent, image_path, type) VALUES ('Scott', 'Hill climber.', 'Ransom', 20, 50, 2.5, 20.9, 2499.00, 1, 6, false, '/assets/e-bikes/scott-ransom/scott-ransom-white.png', 1);

INSERT INTO public.product (name, model, price, color, available_quantity, image_path, type) VALUES ('Alpina', 'Carapax 2.0', 85.99, 3, 2, '/assets/helmets/alpina/alpina_black.png', 3);
INSERT INTO public.product (name, model, price, color, available_quantity, image_path, type) VALUES ('Alpina', 'Plose Mips', 99.95, 5, 3, '/assets/helmets/alpina/alpina_orange.png', 3);
INSERT INTO public.product (name, model, price, color, available_quantity, image_path, type) VALUES ('Alpina', 'Plose Mips', 99.95, 6, 3, '/assets/helmets/alpina/alpina_pink.png', 3);
INSERT INTO public.product (name, model, price, color, available_quantity, image_path, type) VALUES ('Alpina', 'Panoma 2.0', 35.99, 1, 9, '/assets/helmets/alpina/alpina_white.png', 3);